# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_log',
            field=models.FileField(upload_to=b''),
        ),
    ]
